services:
  spy-search:
    build: .
    container_name: spy-search
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - OLLAMA_HOST=host.docker.internal
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped