services:
  - type: web
    name: spy-search
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    autoDeploy: true
